version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - chmod +x ./HelloWorldFunction/mvnw
      - cd HelloWorldFunction
      - ./mvnw clean package
      - sudo apt-get update
      - sudo apt-get install build-essential libbz2-dev liblzma-dev libncurses5-dev libncursesw5-dev libcurl4-gnutls-dev libssl-dev libxml2-dev zlib1g-dev
      - wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2
      - tar xvf samtools-1.11.tar.bz2
      - cd samtools-1.11
      - make
      - sudo make install
      - sam build
artifacts:
  files:
    - target/*.jar
  discard-paths: yes