version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - chmod +x ./HelloWorldFunction/mvnw
      - cd HelloWorldFunction
      - ./mvnw clean package
      - sudo yum update
      - sudo yum install bzip2-devel ncurses-devel curl-devel openssl-devel libxml2-devel zlib-devel
      - wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2
      - tar xvf samtools-1.11.tar.bz2
      - cd samtools-1.11
      - make
      - sudo make install
      - sam build
artifacts:
  files:
    - target/*.jar
  discard-paths: yes