version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase
  build:
    commands:
      - chmod +x ./HelloWorldFunction/mvnw
      - ./HelloWorldFunction/mvnw clean package
      - sam build
artifacts:
  files:
    - target/*.jar
  discard-paths: yes